### ISSUE TITLE
Login y Registro

### ISSUE THREAD

**Issue by carloscastromx** [carloscastromx/vinos-del-valle#3]
Ya que ya está el diseño del login y registro, creo que ya podemos subirlo a Hostinger para que sea funcional, @PAKOEXE403 ¿Puedes crear una tabla en la BD de Usuarios o Clientes para guardar ahi los datos de los que se van a registar? (Usa los datos que puso @Danjune en el formulario de registro).

Yo hago el PHP para validar los datos y registrarlos en la BD cuando se registren y validar si son correctos los datos para el login

Necesitaría el nombre de la base y la contraseña que configuraste @PAKOEXE403 cuando la creaste para conectarme desde PHP

**Comment by Rogelio2001** [comment]
De hecho hoy terminaremos todo el esqueleto de la pagina para que puedas hacer ya el php sin problemas, ahorita subo lo de hostinger y te aviso 


Las credenciales de la base: 
@carloscastromx 
Usuario: u480286810_Raul
Contraseña: wEbwo4-robmew-mivnir

**Comment by carloscastromx** [comment]
@Rogelio2001 Va, para poder tener listo el login, registro y mostrar los productos de la BD en la página de Vinos

**Comment by PAKOEXE403** [comment]
https://discord.gg/KqMDftCt

**Comment by carloscastromx** [comment]
Login: https://vinosdelvalle.store/login/
Registro: https://vinosdelvalle.store/registro/
